name: Build and Deploy
on: 
  push:
     branches:
       - develop 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      # 缓存依赖项: https://docs.github.com/cn/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          # path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
            
      

      - name: Install Dependencies
        run: |
          npm install
        working-directory: ./blog
      
      - name: Look Path
        run: pwd

      - name: Build
        run: |
          npm run build
          # rsync -f ../README.md ./public/README.md
          # rsync -f ../CNAME ./public/CNAME
          # rsync -r ../love ./public/love
          # rsync -r ../project ./public/project
        working-directory: ./blog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./blog/public
          publish_branch: gh-pages
