name: Build and Deploy
on: 
  push:
     branches:
       - develop 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      # 缓存依赖项: https://docs.github.com/cn/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          # path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install
        working-directory: ./blog
      
      - name: Clear Publish Directory
        run: rm -rf public/*
        working-directory: ./blog

      - name: Build
        run: |
          hexo clean && hexo generate
        working-directory: ./blog

      - name: Copy File
        run: |
          cp -r ./README.md ./blog/public/README.md
          cp -r ./love ./blog/public/love
          cp -r ./project ./blog/public/project
        working-directory: ./
          
      - name: Deploy to docs Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./blog/public
          publish_branch: master
